image: phpdockerio/php74-cli

cache:
  paths:
    - ./vendor/

before_script:
  - apt-get update
  - apt-get install -yqq git php-memcached php7.4-mysql php7.4-pgsql php-redis php7.4-sqlite3 php-xdebug php7.4-bcmath php7.4-bz2 php7.4-gd php7.4-gmp php-imagick php7.4-imap php7.4-intl php7.4-soap php-ssh2 php7.4-xsl
  - apt-get clean
  - rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*
  - apt-get update -yqq
  - composer config cache-files-dir ./cache/composer
  - composer install --no-progress --no-suggest

stages:
  - test
phpstan:
  only:
    - merge_requests
    - pipelines
    - pushes
  stage: test
  script:
    - vendor/bin/phpstan analyse -c phpstan.neon --memory-limit=1024M